### ISSUE TITLE
Wilhelm's Crypt Book Crashes Server When Binding is Attempted

### ISSUE THREAD

**Issue by LiskaQuicksilver** [rockfireredmoon/iceee#425]
Basically, when trying to craft the Wilhelm's Crypt Book, adding any component into the Book Binding window seems to crash the server.

Apparently this is the only known Book (so far) that appears to have this issue.

**Comment by rockfireredmoon** [comment]
Fixed

**Comment by LiskaQuicksilver** [comment]
This book still crashes the server along with several others that have been found to do the same. It is quickly becoming apparent that nearly all the Books are crashing the server on Craft.

**Comment by LiskaQuicksilver** [comment]
All Books now craft as intended!
