### ISSUE TITLE
Misplaced Enemy? -Warpig Brewmaster (lvl25-nonheroic) in Johan's Farm (New Badari)

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#460]
Reported By: Galen Jarrus
Category: MOB

I'm not entirely sure, but I think this  guy might have gotten lost. Spawned in Johan's Farm with the Madcows near the pond/water (southwest corner).

**Comment by LiskaQuicksilver** [comment]
Okay, I've checked for this on both the test server and live server. I was able to verify this one on the live server previously; however, I have checked again and either this issue was already fixed or it resolved itself. Either way, the affected spawn point is now once again a Mad Cow mob as it should be.

**Comment by rockfireredmoon** [comment]
Fixed. This was a shared spawn package that uses a 'Divider'. Have got rid of this so it uses two separate spawn packages.

**Comment by LiskaQuicksilver** [comment]
As much as I want to say you fixed the issue, this is unfortunately not the case. Whatever you did with the spawn packages, it seems the affected spawns are not only still broken, but, now they randomly spawn nothing at all.

I have tested this at the Mad Cow Farm, the Dunklehimer Brewery Camp and the Scallywag Road Ambush spot. Some spots spawned nothing period, or spawned mobs for a time but then stopped after several kills in that spot. At the Mad Cow Farm, I even forcibly spawned a mob at the originally affected spot which took a few tries before succeeding. After defeating a mere two mobs (the one I force-spawned and one that spawned normally afterward) in that location, the mobs stopped spawning there again.

Might want to re-evaluate whatever the change was in case you overlooked a crucial detail in the earlier setup.

**Comment by rockfireredmoon** [comment]
It appears that scenery saving was wiping out outerRadius attribute (and innerRadius) for many spawn points in the same tile. I also made sure it it is saved with a blank name if the name is 'Untitled'.  Also moved spawnPackage to end of list. This should make pages save in the same format as more scenery is currently stored.

The spawning now seems to be correct to me.

**Comment by rockfireredmoon** [comment]
Confirmed fixed by @LiskaQuicksilver
