### ISSUE TITLE
Mistake in Maximum Amount of Items error message.

### ISSUE THREAD

**Issue by LiskaQuicksilver** [rockfireredmoon/iceee#828]
This is the error message players get when they attempt to claim a second copy of a one-time-only item in the game. Unfortunately this message currently states the following:
"You already the maximum amount of these items."

It should say either:
"You already have the maximum amount of these items." or "You already have the maximum amount of this item."

I discovered this mistake while testing the Bounders Day quests, though I believe it is used in other areas of the game as well.

**Comment by rockfireredmoon** [comment]
Fixed

**Comment by LiskaQuicksilver** [comment]
Going to hazard you did not update the server because the error still exists.

**Comment by rockfireredmoon** [comment]
I did, but it turns out there are 3 different occurrences of this error. I only changed the first.

**Comment by LiskaQuicksilver** [comment]
This is finally resolved.
